spring:
  jwt:
    secret: {secret}


cloud:
  aws:
    s3:
      bucket: {review-img-bucket}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: {accessKey}
      secretKey: {secretKey}
